export const SKILLS_ICONS: Record<string, string>= {
    javascript: "/skills/javascript.svg",
    typescript: "/skills/typescript.svg",
    react: "/skills/react.svg",
    node: "/skills/nodejs.svg",
    next: "/skills/nextjs.svg",
    python: "/skills/python.svg",
    java: "/skills/java.svg",
    docker: "/skills/docker.svg",
    postgresql: "/skills/postgresql.svg",
    mysql: "/skills/mysql.svg",
    firebase: "/skills/firebase.svg",
    googleCloud: "/skills/google-cloud.svg",
    springBoot: "/skills/spring-boot.svg",
    html: "/skills/html.svg",
    css: "/skills/css.svg",
    tailwind: "/skills/tailwind.svg",
    gpt: "/skills/gpt.svg",
    astro: "/skills/astro.svg",
    django: "/skills/django.svg",
    express: "/skills/express.svg",
    git: "/skills/git.svg",
    github: "/skills/github.svg",
    reactNative: "/skills/react.svg",
    flutter: "/skills/flutter.svg",
    gemini: "/skills/gemini.svg",
    googleSheets: "/skills/google-sheets.svg",
}